### ISSUE TITLE
Module Not Found: bcrypt

### ISSUE THREAD

**Issue by fmarques899** [nicknux/jwtserver#1]
I'm having problem to start the app, because when I try to start with 
> $ python3 main.py

I get the following message error:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import auth
  File "/Users/felipe/pythonworkspace/jwtserver/auth.py", line 5, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'

**Comment by nicknux** [comment]
This project requires virtualenv. Here's a helpful guide on setting it up and using the included `requirements.txt` with it -- http://docs.python-guide.org/en/latest/dev/virtualenvs/
